title: Dwija Parikh
baseurl: ""
url: "https://dwijap.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"
remote_theme: ankitsultana/researcher@gem

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Projects"
   link: "/projects/"
 - name: "CV"
   link: "Dwija_Parikh_CV.pdf"
 - name: "Blog"
   link: "/blog/"
   
